///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexMergeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexMergeTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("32295630-aeeb-42cd-b32b-aef0c7664898")]
    public partial class RanorexMergeTestRepository : RepoGenBaseFolder
    {
        static RanorexMergeTestRepository instance = new RanorexMergeTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the RanorexMergeTestRepository element repository.
        /// </summary>
        [RepositoryFolder("32295630-aeeb-42cd-b32b-aef0c7664898")]
        public static RanorexMergeTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexMergeTestRepository() 
            : base("RanorexMergeTestRepository", "/", null, 0, false, "32295630-aeeb-42cd-b32b-aef0c7664898", ".\\RepositoryImages\\RanorexMergeTestRepository32295630.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("32295630-aeeb-42cd-b32b-aef0c7664898")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexMergeTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
